# Create a new user

POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.test",
  "name": "Name Test",
  "password": "123456"
}

###


# Add avatar to user

POST http://localhost:4000/api/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDY1MjI0MjgsImV4cCI6MTcwNjYwODgyOH0.elEA_eRai5A-QHs4O2YIpHRBsLJlns22NAeFbBD8f-Y
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="avatar.jpg"

< ./avatar.jpg

--boundary--

###


# Create a new user by authorized user (1.1)

POST http://localhost:4000/api/users/register HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWIyOWM0NmY0ZmI5NzA0NWQxYjJlY2IiLCJlbWFpbCI6Im5ld3Vpc2VyQGVtYWlsLnRlc3QiLCJuYW1lIjoiVXNlciBOYW1lIiwiaWF0IjoxNzA2Mjc1NjE5LCJleHAiOjE3MDYzNjIwMTl9.hm-3E8ugDrlYQvmvMM0oo0UKDO9d0UY3aeQ4RrsZNqc
Content-Type: application/json

{
  "email": "user@email.test",
  "name": "Name Test",
  "password": "123456"
}

###


# Login user by email and password

POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.test",
  "password": "123456"
}

###


# Get user info

GET http://localhost:4000/api/users/6580462f5e238357ab17003a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDYxOTYwMTgsImV4cCI6MTcwNjI4MjQxOH0.Zxq0Rp_FuQBqUaf5OYiNysqKF46YS7srH7jLxTSQqBw

###


# Update user

PATCH http://localhost:4000/api/users/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDY1MjI0MjgsImV4cCI6MTcwNjYwODgyOH0.elEA_eRai5A-QHs4O2YIpHRBsLJlns22NAeFbBD8f-Y
Content-Type: application/json

{
  "name": "Update Name"
}

###


# Get new JWT pair

POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJ0b2tlbklkIjoiMWVjMzExMzEtNTBlMS00ZjcwLWE0MWMtZjZlNDUxOWU5OTJmIiwiaWF0IjoxNzA2MTEzNDE1LCJleHAiOjE3MDY5Nzc0MTV9.jbdyyNdAToamKDc9ELFd0WjSjk3ZBIvOx2zPCrsUc6s

###


# Change password (1.9)

POST http://localhost:4000/api/users/password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDYyNzcxMzYsImV4cCI6MTcwNjM2MzUzNn0.YI_tFaDOzhgpoVcdRjTwhfo-ZnsQbIOvbfU48rZ_sgk
Content-Type: application/json

{
  "userId": "6580462f5e238357ab17003a",
  "password": "qwerty",
  "newPassword": "123456"
}

###
