# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.test",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJ0b2tlbklkIjoiNmE3N2JiMmQtYzZiZC00ZTdmLThjZGUtMmVmZGFjZjJmYTU4IiwiaWF0IjoxNzA1ODQ2OTc0LCJleHAiOjE3MDY3MTA5NzR9.GDmc-QeLWVKgc4CzFEfQw8EypnRol3hISanXuL6lpP0

###

# Create a new post
POST http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDU4NDg5MDcsImV4cCI6MTcwNTkzNTMwN30.T7CrLoZQvLJ9zx_KxcXNXMUmUVOnGFYTKGOWBp-RnIk
Content-Type: application/json

{
  "postType": "quote",
  "text": "Проверка сервиса API",
  "author": "Какой-то автор",
  "tags": ["ad48ef46-6ea6-41c4-a19f-e66b82bdf855"]
}
###

# Get all posts
GET http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgwNDYyZjVlMjM4MzU3YWIxNzAwM2EiLCJlbWFpbCI6InVzZXJAZW1haWwudGVzdCIsIm5hbWUiOiJUZXN0IE5hbWUiLCJpYXQiOjE3MDU4NDg5MDcsImV4cCI6MTcwNTkzNTMwN30.T7CrLoZQvLJ9zx_KxcXNXMUmUVOnGFYTKGOWBp-RnIk
