# Get all posts

GET http://localhost:3030/api/posts HTTP/1.1

###

# Get posts with filter

GET http://localhost:3030/api/posts?tags[]=ad48ef46-6ea6-41c4-a19f-e66b82bdf855&limit=5&sortDirection=asc&page=1 HTTP/1.1

###

# Get posts with filter userId

GET http://localhost:3030/api/posts?sortDirection=desc&userId=658170cbb954e9f5b905ccf4 HTTP/1.1

###


# Get posts with sort type by likes count

GET http://localhost:3030/api/posts?sortType=comments&sortDirection=asc HTTP/1.1

###


# Get post by id

GET http://localhost:3030/api/posts/7e887c7f-1d9f-459a-ba81-c3e111d24bf5 HTTP/1.1

###

# Create a new TEXT post

POST http://localhost:3030/api/posts HTTP/1.1
Content-Type: application/json

{
  "postType": "text",
  "title": "Заголовок тестового",
  "text": "Это цитата для проверки",
  "userId": "6580462f5e238357ab17003a",
  "tags": ["ad48ef46-6ea6-41c4-a19f-e66b82bdf855"]
}

###

# Create a new post

POST http://localhost:3030/api/posts HTTP/1.1
Content-Type: application/json

{
  "postType": "quote",
  "text": "Это цитата для проверки",
  "author": "Какой-то автор",
  "userId": "6580462f5e238357ab17003a",
  "tags": ["ad48ef46-6ea6-41c4-a19f-e66b82bdf855"]
}

###


# Repost

POST http://localhost:3030/api/posts/repost/5f37facf-ca8f-408d-98e3-c03b6951747b HTTP/1.1
Content-Type: application/json

{
  "userId": "65ad1a9709d14f464142a4be"
}

###


# Delete the post by id

DELETE http://localhost:3030/api/posts/ab04593b-da99-4fe3-8b4b-e06d82e2efdd HTTP/1.1
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905ccf4"
}

###

# Update post by id

PATCH http://localhost:3030/api/posts/7e887c7f-1d9f-459a-ba81-c3e111d24bf5 HTTP/1.1
Content-Type: application/json

{
  "author": "Обновленный автор цитаты",
  "userId": "6580462f5e238357ab17003a"
}

###


# Update post status by id

PATCH http://localhost:3030/api/posts/status/6d308040-96a2-4162-bea6-2338e9976540 HTTP/1.1
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905ccf4"
}

###


# Toggle like

PATCH http://localhost:3030/api/posts/like/a781c089-8465-413a-989a-1a9e84107516 HTTP/1.1
Content-Type: application/json

{
  "likeId": "6580462f5e238357ab17003a"
}
