# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.test",
  "name": "Test Name",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/6580462f5e238357ab17003a HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.test",
  "password": "123456"
}

###
